%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

SerialNumber: "00G88325507"

CameraName: "left"

# Ros topic name
TopicName: "left_camera/image"

# Exposure Auto, 0 stands for Off, 1 stands for Once, 2 stands for Continues
# ExposureAuto: 2
# AutoExposureTimeLower: 65
# AutoExposureTimeUpper: 10000


ExposureAuto: 0
ExposureTime: 1000


# Gain Auto, 0 stands for Off, 1 stands for Once, 2 stands for Continues
GainAuto: 2

# Gamma Selector, 0 stands for user, 1 stands for sRGB
GammaSelector: 1

# Frame Rate (if trigger mode is on, frame rate is enable)
FrameRate: 10.0
